/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace SimplePrivacyAccount {
  export type ChainSplitStruct = {
    chainId: BigNumberish;
    amount: BigNumberish;
    targetContract: AddressLike;
  };

  export type ChainSplitStructOutput = [
    chainId: bigint,
    amount: bigint,
    targetContract: string
  ] & { chainId: bigint; amount: bigint; targetContract: string };
}

export interface SimplePrivacyAccountInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "execute"
      | "executeBatch"
      | "initiateMultiChainPayment"
      | "makePrivacyPayment"
      | "owner"
      | "privacyEnabled"
      | "privacyTreeContract"
      | "recoverERC20"
      | "recoverETH"
      | "renounceOwnership"
      | "setPrivacyEnabled"
      | "setPrivacyTree"
      | "transferOwnership"
      | "withdrawFromPrivacyPool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Executed"
      | "MultiChainPaymentSplit"
      | "OwnershipTransferred"
      | "PrivacyPaymentInitiated"
      | "PrivacyToggled"
      | "PrivacyTreeUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [AddressLike[], BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateMultiChainPayment",
    values: [
      BigNumberish,
      SimplePrivacyAccount.ChainSplitStruct[],
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "makePrivacyPayment",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "privacyEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "privacyTreeContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recoverERC20",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPrivacyEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrivacyTree",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromPrivacyPool",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      [BigNumberish],
      BytesLike,
      AddressLike,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateMultiChainPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makePrivacyPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "privacyEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "privacyTreeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recoverETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPrivacyEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPrivacyTree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromPrivacyPool",
    data: BytesLike
  ): Result;
}

export namespace ExecutedEvent {
  export type InputTuple = [
    target: AddressLike,
    value: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [target: string, value: bigint, data: string];
  export interface OutputObject {
    target: string;
    value: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultiChainPaymentSplitEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    splits: SimplePrivacyAccount.ChainSplitStruct[]
  ];
  export type OutputTuple = [
    paymentId: bigint,
    splits: SimplePrivacyAccount.ChainSplitStructOutput[]
  ];
  export interface OutputObject {
    paymentId: bigint;
    splits: SimplePrivacyAccount.ChainSplitStructOutput[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivacyPaymentInitiatedEvent {
  export type InputTuple = [commitment: BytesLike, amount: BigNumberish];
  export type OutputTuple = [commitment: string, amount: bigint];
  export interface OutputObject {
    commitment: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivacyToggledEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivacyTreeUpdatedEvent {
  export type InputTuple = [newTree: AddressLike];
  export type OutputTuple = [newTree: string];
  export interface OutputObject {
    newTree: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimplePrivacyAccount extends BaseContract {
  connect(runner?: ContractRunner | null): SimplePrivacyAccount;
  waitForDeployment(): Promise<this>;

  interface: SimplePrivacyAccountInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  execute: TypedContractMethod<
    [target: AddressLike, value: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  executeBatch: TypedContractMethod<
    [targets: AddressLike[], values: BigNumberish[], datas: BytesLike[]],
    [void],
    "nonpayable"
  >;

  initiateMultiChainPayment: TypedContractMethod<
    [
      paymentId: BigNumberish,
      splits: SimplePrivacyAccount.ChainSplitStruct[],
      token: AddressLike,
      totalAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  makePrivacyPayment: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, commitment: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  privacyEnabled: TypedContractMethod<[], [boolean], "view">;

  privacyTreeContract: TypedContractMethod<[], [string], "view">;

  recoverERC20: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recoverETH: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPrivacyEnabled: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  setPrivacyTree: TypedContractMethod<
    [_privacyTree: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFromPrivacyPool: TypedContractMethod<
    [
      pA: [BigNumberish, BigNumberish],
      pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pC: [BigNumberish, BigNumberish],
      pubSignals: [BigNumberish],
      nullifier: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [target: AddressLike, value: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeBatch"
  ): TypedContractMethod<
    [targets: AddressLike[], values: BigNumberish[], datas: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initiateMultiChainPayment"
  ): TypedContractMethod<
    [
      paymentId: BigNumberish,
      splits: SimplePrivacyAccount.ChainSplitStruct[],
      token: AddressLike,
      totalAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "makePrivacyPayment"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, commitment: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "privacyEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "privacyTreeContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recoverERC20"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recoverETH"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrivacyEnabled"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrivacyTree"
  ): TypedContractMethod<[_privacyTree: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFromPrivacyPool"
  ): TypedContractMethod<
    [
      pA: [BigNumberish, BigNumberish],
      pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pC: [BigNumberish, BigNumberish],
      pubSignals: [BigNumberish],
      nullifier: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Executed"
  ): TypedContractEvent<
    ExecutedEvent.InputTuple,
    ExecutedEvent.OutputTuple,
    ExecutedEvent.OutputObject
  >;
  getEvent(
    key: "MultiChainPaymentSplit"
  ): TypedContractEvent<
    MultiChainPaymentSplitEvent.InputTuple,
    MultiChainPaymentSplitEvent.OutputTuple,
    MultiChainPaymentSplitEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PrivacyPaymentInitiated"
  ): TypedContractEvent<
    PrivacyPaymentInitiatedEvent.InputTuple,
    PrivacyPaymentInitiatedEvent.OutputTuple,
    PrivacyPaymentInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "PrivacyToggled"
  ): TypedContractEvent<
    PrivacyToggledEvent.InputTuple,
    PrivacyToggledEvent.OutputTuple,
    PrivacyToggledEvent.OutputObject
  >;
  getEvent(
    key: "PrivacyTreeUpdated"
  ): TypedContractEvent<
    PrivacyTreeUpdatedEvent.InputTuple,
    PrivacyTreeUpdatedEvent.OutputTuple,
    PrivacyTreeUpdatedEvent.OutputObject
  >;

  filters: {
    "Executed(address,uint256,bytes)": TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
    Executed: TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;

    "MultiChainPaymentSplit(uint256,tuple[])": TypedContractEvent<
      MultiChainPaymentSplitEvent.InputTuple,
      MultiChainPaymentSplitEvent.OutputTuple,
      MultiChainPaymentSplitEvent.OutputObject
    >;
    MultiChainPaymentSplit: TypedContractEvent<
      MultiChainPaymentSplitEvent.InputTuple,
      MultiChainPaymentSplitEvent.OutputTuple,
      MultiChainPaymentSplitEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PrivacyPaymentInitiated(bytes32,uint256)": TypedContractEvent<
      PrivacyPaymentInitiatedEvent.InputTuple,
      PrivacyPaymentInitiatedEvent.OutputTuple,
      PrivacyPaymentInitiatedEvent.OutputObject
    >;
    PrivacyPaymentInitiated: TypedContractEvent<
      PrivacyPaymentInitiatedEvent.InputTuple,
      PrivacyPaymentInitiatedEvent.OutputTuple,
      PrivacyPaymentInitiatedEvent.OutputObject
    >;

    "PrivacyToggled(bool)": TypedContractEvent<
      PrivacyToggledEvent.InputTuple,
      PrivacyToggledEvent.OutputTuple,
      PrivacyToggledEvent.OutputObject
    >;
    PrivacyToggled: TypedContractEvent<
      PrivacyToggledEvent.InputTuple,
      PrivacyToggledEvent.OutputTuple,
      PrivacyToggledEvent.OutputObject
    >;

    "PrivacyTreeUpdated(address)": TypedContractEvent<
      PrivacyTreeUpdatedEvent.InputTuple,
      PrivacyTreeUpdatedEvent.OutputTuple,
      PrivacyTreeUpdatedEvent.OutputObject
    >;
    PrivacyTreeUpdated: TypedContractEvent<
      PrivacyTreeUpdatedEvent.InputTuple,
      PrivacyTreeUpdatedEvent.OutputTuple,
      PrivacyTreeUpdatedEvent.OutputObject
    >;
  };
}
