/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AccountFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accountImplementation"
      | "allAccounts"
      | "batchCreateAccounts"
      | "createAccount"
      | "entryPoint"
      | "getAccountCount"
      | "getAccountForOwner"
      | "getAddress"
      | "getAllAccounts"
      | "isAccount"
      | "owner"
      | "ownerToAccount"
      | "privacyTreeContract"
      | "renounceOwnership"
      | "transferOwnership"
      | "updatePrivacyTree"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccountCreated"
      | "OwnershipTransferred"
      | "PrivacyTreeUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accountImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allAccounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCreateAccounts",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createAccount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountForOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAccounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerToAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "privacyTreeContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrivacyTree",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCreateAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccountCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountForOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAccount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerToAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "privacyTreeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrivacyTree",
    data: BytesLike
  ): Result;
}

export namespace AccountCreatedEvent {
  export type InputTuple = [
    owner: AddressLike,
    account: AddressLike,
    salt: BigNumberish
  ];
  export type OutputTuple = [owner: string, account: string, salt: bigint];
  export interface OutputObject {
    owner: string;
    account: string;
    salt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivacyTreeUpdatedEvent {
  export type InputTuple = [oldTree: AddressLike, newTree: AddressLike];
  export type OutputTuple = [oldTree: string, newTree: string];
  export interface OutputObject {
    oldTree: string;
    newTree: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AccountFactory extends BaseContract {
  connect(runner?: ContractRunner | null): AccountFactory;
  waitForDeployment(): Promise<this>;

  interface: AccountFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accountImplementation: TypedContractMethod<[], [string], "view">;

  allAccounts: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  batchCreateAccounts: TypedContractMethod<
    [owners: AddressLike[], salts: BigNumberish[]],
    [string[]],
    "nonpayable"
  >;

  createAccount: TypedContractMethod<
    [owner: AddressLike, salt: BigNumberish],
    [string],
    "nonpayable"
  >;

  entryPoint: TypedContractMethod<[], [string], "view">;

  getAccountCount: TypedContractMethod<[], [bigint], "view">;

  getAccountForOwner: TypedContractMethod<
    [owner: AddressLike],
    [string],
    "view"
  >;

  getAddress: TypedContractMethod<
    [owner: AddressLike, salt: BigNumberish],
    [string],
    "view"
  >;

  getAllAccounts: TypedContractMethod<[], [string[]], "view">;

  isAccount: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerToAccount: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  privacyTreeContract: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePrivacyTree: TypedContractMethod<
    [_newPrivacyTree: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accountImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allAccounts"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "batchCreateAccounts"
  ): TypedContractMethod<
    [owners: AddressLike[], salts: BigNumberish[]],
    [string[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createAccount"
  ): TypedContractMethod<
    [owner: AddressLike, salt: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "entryPoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAccountCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAccountForOwner"
  ): TypedContractMethod<[owner: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<
    [owner: AddressLike, salt: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllAccounts"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isAccount"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerToAccount"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "privacyTreeContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePrivacyTree"
  ): TypedContractMethod<[_newPrivacyTree: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AccountCreated"
  ): TypedContractEvent<
    AccountCreatedEvent.InputTuple,
    AccountCreatedEvent.OutputTuple,
    AccountCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PrivacyTreeUpdated"
  ): TypedContractEvent<
    PrivacyTreeUpdatedEvent.InputTuple,
    PrivacyTreeUpdatedEvent.OutputTuple,
    PrivacyTreeUpdatedEvent.OutputObject
  >;

  filters: {
    "AccountCreated(address,address,uint256)": TypedContractEvent<
      AccountCreatedEvent.InputTuple,
      AccountCreatedEvent.OutputTuple,
      AccountCreatedEvent.OutputObject
    >;
    AccountCreated: TypedContractEvent<
      AccountCreatedEvent.InputTuple,
      AccountCreatedEvent.OutputTuple,
      AccountCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PrivacyTreeUpdated(address,address)": TypedContractEvent<
      PrivacyTreeUpdatedEvent.InputTuple,
      PrivacyTreeUpdatedEvent.OutputTuple,
      PrivacyTreeUpdatedEvent.OutputObject
    >;
    PrivacyTreeUpdated: TypedContractEvent<
      PrivacyTreeUpdatedEvent.InputTuple,
      PrivacyTreeUpdatedEvent.OutputTuple,
      PrivacyTreeUpdatedEvent.OutputObject
    >;
  };
}
