/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPrivacyMerkleTree,
  IPrivacyMerkleTreeInterface,
} from "../../../contracts/SimplePrivacyAccount.sol/IPrivacyMerkleTree";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "commitment",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "pA",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "pB",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "pC",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[1]",
        name: "pubSignals",
        type: "uint256[1]",
      },
      {
        internalType: "bytes32",
        name: "nullifier",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPrivacyMerkleTree__factory {
  static readonly abi = _abi;
  static createInterface(): IPrivacyMerkleTreeInterface {
    return new Interface(_abi) as IPrivacyMerkleTreeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPrivacyMerkleTree {
    return new Contract(address, _abi, runner) as unknown as IPrivacyMerkleTree;
  }
}
