/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CrossChainRouter {
  export type PaymentSplitStruct = {
    paymentId: BigNumberish;
    sender: AddressLike;
    chainIds: BigNumberish[];
    amounts: BigNumberish[];
    commitments: BytesLike[];
    timestamp: BigNumberish;
    executed: boolean;
  };

  export type PaymentSplitStructOutput = [
    paymentId: bigint,
    sender: string,
    chainIds: bigint[],
    amounts: bigint[],
    commitments: string[],
    timestamp: bigint,
    executed: boolean
  ] & {
    paymentId: bigint;
    sender: string;
    chainIds: bigint[];
    amounts: bigint[];
    commitments: string[];
    timestamp: bigint;
    executed: boolean;
  };
}

export interface CrossChainRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addChain"
      | "calculateOptimalSplit"
      | "chainIdToLzChainId"
      | "chainIdToPrivacyTree"
      | "emergencyWithdraw"
      | "executePaymentSplit"
      | "gasPrice"
      | "getPayment"
      | "getSupportedChains"
      | "initiatePaymentSplit"
      | "lzEndpoint"
      | "lzReceive"
      | "nextPaymentId"
      | "owner"
      | "payments"
      | "removeChain"
      | "renounceOwnership"
      | "supportedChains"
      | "transferOwnership"
      | "updateGasPrice"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChainAdded"
      | "ChainRemoved"
      | "CrossChainMessageSent"
      | "GasPriceUpdated"
      | "OwnershipTransferred"
      | "PaymentSplitExecuted"
      | "PaymentSplitInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addChain",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateOptimalSplit",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "chainIdToLzChainId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "chainIdToPrivacyTree",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executePaymentSplit",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gasPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedChains",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiatePaymentSplit",
    values: [BigNumberish[], BigNumberish[], BytesLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lzEndpoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lzReceive",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPaymentId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportedChains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGasPrice",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addChain", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateOptimalSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "chainIdToLzChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "chainIdToPrivacyTree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePaymentSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiatePaymentSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lzEndpoint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lzReceive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextPaymentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGasPrice",
    data: BytesLike
  ): Result;
}

export namespace ChainAddedEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    lzChainId: BigNumberish,
    privacyTree: AddressLike
  ];
  export type OutputTuple = [
    chainId: bigint,
    lzChainId: bigint,
    privacyTree: string
  ];
  export interface OutputObject {
    chainId: bigint;
    lzChainId: bigint;
    privacyTree: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainRemovedEvent {
  export type InputTuple = [chainId: BigNumberish];
  export type OutputTuple = [chainId: bigint];
  export interface OutputObject {
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainMessageSentEvent {
  export type InputTuple = [paymentId: BigNumberish, dstChainId: BigNumberish];
  export type OutputTuple = [paymentId: bigint, dstChainId: bigint];
  export interface OutputObject {
    paymentId: bigint;
    dstChainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasPriceUpdatedEvent {
  export type InputTuple = [chainId: BigNumberish, gasPrice: BigNumberish];
  export type OutputTuple = [chainId: bigint, gasPrice: bigint];
  export interface OutputObject {
    chainId: bigint;
    gasPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSplitExecutedEvent {
  export type InputTuple = [paymentId: BigNumberish];
  export type OutputTuple = [paymentId: bigint];
  export interface OutputObject {
    paymentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSplitInitiatedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    sender: AddressLike,
    chainIds: BigNumberish[],
    amounts: BigNumberish[],
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: bigint,
    sender: string,
    chainIds: bigint[],
    amounts: bigint[],
    totalAmount: bigint
  ];
  export interface OutputObject {
    paymentId: bigint;
    sender: string;
    chainIds: bigint[];
    amounts: bigint[];
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrossChainRouter extends BaseContract {
  connect(runner?: ContractRunner | null): CrossChainRouter;
  waitForDeployment(): Promise<this>;

  interface: CrossChainRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addChain: TypedContractMethod<
    [chainId: BigNumberish, lzChainId: BigNumberish, privacyTree: AddressLike],
    [void],
    "nonpayable"
  >;

  calculateOptimalSplit: TypedContractMethod<
    [totalAmount: BigNumberish, chainIds: BigNumberish[]],
    [bigint[]],
    "view"
  >;

  chainIdToLzChainId: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  chainIdToPrivacyTree: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executePaymentSplit: TypedContractMethod<
    [paymentId: BigNumberish, token: AddressLike],
    [void],
    "payable"
  >;

  gasPrice: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getPayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [CrossChainRouter.PaymentSplitStructOutput],
    "view"
  >;

  getSupportedChains: TypedContractMethod<[], [bigint[]], "view">;

  initiatePaymentSplit: TypedContractMethod<
    [
      chainIds: BigNumberish[],
      amounts: BigNumberish[],
      commitments: BytesLike[],
      token: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  lzEndpoint: TypedContractMethod<[], [string], "view">;

  lzReceive: TypedContractMethod<
    [
      srcChainId: BigNumberish,
      srcAddress: BytesLike,
      nonce: BigNumberish,
      payload: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  nextPaymentId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        paymentId: bigint;
        sender: string;
        timestamp: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  removeChain: TypedContractMethod<
    [chainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  supportedChains: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateGasPrice: TypedContractMethod<
    [chainId: BigNumberish, _gasPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addChain"
  ): TypedContractMethod<
    [chainId: BigNumberish, lzChainId: BigNumberish, privacyTree: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateOptimalSplit"
  ): TypedContractMethod<
    [totalAmount: BigNumberish, chainIds: BigNumberish[]],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "chainIdToLzChainId"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "chainIdToPrivacyTree"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executePaymentSplit"
  ): TypedContractMethod<
    [paymentId: BigNumberish, token: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "gasPrice"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BigNumberish],
    [CrossChainRouter.PaymentSplitStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupportedChains"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "initiatePaymentSplit"
  ): TypedContractMethod<
    [
      chainIds: BigNumberish[],
      amounts: BigNumberish[],
      commitments: BytesLike[],
      token: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lzEndpoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lzReceive"
  ): TypedContractMethod<
    [
      srcChainId: BigNumberish,
      srcAddress: BytesLike,
      nonce: BigNumberish,
      payload: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextPaymentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        paymentId: bigint;
        sender: string;
        timestamp: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedChains"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateGasPrice"
  ): TypedContractMethod<
    [chainId: BigNumberish, _gasPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ChainAdded"
  ): TypedContractEvent<
    ChainAddedEvent.InputTuple,
    ChainAddedEvent.OutputTuple,
    ChainAddedEvent.OutputObject
  >;
  getEvent(
    key: "ChainRemoved"
  ): TypedContractEvent<
    ChainRemovedEvent.InputTuple,
    ChainRemovedEvent.OutputTuple,
    ChainRemovedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainMessageSent"
  ): TypedContractEvent<
    CrossChainMessageSentEvent.InputTuple,
    CrossChainMessageSentEvent.OutputTuple,
    CrossChainMessageSentEvent.OutputObject
  >;
  getEvent(
    key: "GasPriceUpdated"
  ): TypedContractEvent<
    GasPriceUpdatedEvent.InputTuple,
    GasPriceUpdatedEvent.OutputTuple,
    GasPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSplitExecuted"
  ): TypedContractEvent<
    PaymentSplitExecutedEvent.InputTuple,
    PaymentSplitExecutedEvent.OutputTuple,
    PaymentSplitExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSplitInitiated"
  ): TypedContractEvent<
    PaymentSplitInitiatedEvent.InputTuple,
    PaymentSplitInitiatedEvent.OutputTuple,
    PaymentSplitInitiatedEvent.OutputObject
  >;

  filters: {
    "ChainAdded(uint256,uint16,address)": TypedContractEvent<
      ChainAddedEvent.InputTuple,
      ChainAddedEvent.OutputTuple,
      ChainAddedEvent.OutputObject
    >;
    ChainAdded: TypedContractEvent<
      ChainAddedEvent.InputTuple,
      ChainAddedEvent.OutputTuple,
      ChainAddedEvent.OutputObject
    >;

    "ChainRemoved(uint256)": TypedContractEvent<
      ChainRemovedEvent.InputTuple,
      ChainRemovedEvent.OutputTuple,
      ChainRemovedEvent.OutputObject
    >;
    ChainRemoved: TypedContractEvent<
      ChainRemovedEvent.InputTuple,
      ChainRemovedEvent.OutputTuple,
      ChainRemovedEvent.OutputObject
    >;

    "CrossChainMessageSent(uint256,uint256)": TypedContractEvent<
      CrossChainMessageSentEvent.InputTuple,
      CrossChainMessageSentEvent.OutputTuple,
      CrossChainMessageSentEvent.OutputObject
    >;
    CrossChainMessageSent: TypedContractEvent<
      CrossChainMessageSentEvent.InputTuple,
      CrossChainMessageSentEvent.OutputTuple,
      CrossChainMessageSentEvent.OutputObject
    >;

    "GasPriceUpdated(uint256,uint256)": TypedContractEvent<
      GasPriceUpdatedEvent.InputTuple,
      GasPriceUpdatedEvent.OutputTuple,
      GasPriceUpdatedEvent.OutputObject
    >;
    GasPriceUpdated: TypedContractEvent<
      GasPriceUpdatedEvent.InputTuple,
      GasPriceUpdatedEvent.OutputTuple,
      GasPriceUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentSplitExecuted(uint256)": TypedContractEvent<
      PaymentSplitExecutedEvent.InputTuple,
      PaymentSplitExecutedEvent.OutputTuple,
      PaymentSplitExecutedEvent.OutputObject
    >;
    PaymentSplitExecuted: TypedContractEvent<
      PaymentSplitExecutedEvent.InputTuple,
      PaymentSplitExecutedEvent.OutputTuple,
      PaymentSplitExecutedEvent.OutputObject
    >;

    "PaymentSplitInitiated(uint256,address,uint256[],uint256[],uint256)": TypedContractEvent<
      PaymentSplitInitiatedEvent.InputTuple,
      PaymentSplitInitiatedEvent.OutputTuple,
      PaymentSplitInitiatedEvent.OutputObject
    >;
    PaymentSplitInitiated: TypedContractEvent<
      PaymentSplitInitiatedEvent.InputTuple,
      PaymentSplitInitiatedEvent.OutputTuple,
      PaymentSplitInitiatedEvent.OutputObject
    >;
  };
}
