/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILayerZeroEndpoint,
  ILayerZeroEndpointInterface,
} from "../../../contracts/CrossChainRouter.sol/ILayerZeroEndpoint";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint16",
        name: "dstChainId",
        type: "uint16",
      },
      {
        internalType: "bytes",
        name: "destination",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
      {
        internalType: "address payable",
        name: "refundAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "zroPaymentAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "adapterParams",
        type: "bytes",
      },
    ],
    name: "send",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ILayerZeroEndpoint__factory {
  static readonly abi = _abi;
  static createInterface(): ILayerZeroEndpointInterface {
    return new Interface(_abi) as ILayerZeroEndpointInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILayerZeroEndpoint {
    return new Contract(address, _abi, runner) as unknown as ILayerZeroEndpoint;
  }
}
