/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  AccountProxy,
  AccountProxyInterface,
} from "../../../contracts/AccountFactory.sol/AccountProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_implementation",
        type: "address",
      },
      {
        internalType: "address",
        name: "_entryPoint",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "entryPoint",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60c060405234801561001057600080fd5b5060405161031c38038061031c83398181016040528101906100329190610104565b8173ffffffffffffffffffffffffffffffffffffffff1660808173ffffffffffffffffffffffffffffffffffffffff16815250508073ffffffffffffffffffffffffffffffffffffffff1660a08173ffffffffffffffffffffffffffffffffffffffff16815250505050610144565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100d1826100a6565b9050919050565b6100e1816100c6565b81146100ec57600080fd5b50565b6000815190506100fe816100d8565b92915050565b6000806040838503121561011b5761011a6100a1565b5b6000610129858286016100ef565b925050602061013a858286016100ef565b9150509250929050565b60805160a0516101af61016d600039600060fb0152600081816038015260d701526101af6000f3fe60806040526004361061002d5760003560e01c80635c60da1b1461007f578063b0d691fe146100aa57610034565b3661003457005b60007f000000000000000000000000000000000000000000000000000000000000000090503660008037600080366000845af43d6000803e806000811461007a573d6000f35b3d6000fd5b34801561008b57600080fd5b506100946100d5565b6040516100a1919061015e565b60405180910390f35b3480156100b657600080fd5b506100bf6100f9565b6040516100cc919061015e565b60405180910390f35b7f000000000000000000000000000000000000000000000000000000000000000081565b7f000000000000000000000000000000000000000000000000000000000000000081565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101488261011d565b9050919050565b6101588161013d565b82525050565b6000602082019050610173600083018461014f565b9291505056fea26469706673582212206086f4aa49ab6592f65edc64171a5a8413af8afe87d2d1c52d3e5f26a900c62564736f6c634300081c0033";

type AccountProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AccountProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AccountProxy__factory extends ContractFactory {
  constructor(...args: AccountProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _implementation: AddressLike,
    _entryPoint: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      _implementation,
      _entryPoint,
      overrides || {}
    );
  }
  override deploy(
    _implementation: AddressLike,
    _entryPoint: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(
      _implementation,
      _entryPoint,
      overrides || {}
    ) as Promise<
      AccountProxy & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AccountProxy__factory {
    return super.connect(runner) as AccountProxy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AccountProxyInterface {
    return new Interface(_abi) as AccountProxyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AccountProxy {
    return new Contract(address, _abi, runner) as unknown as AccountProxy;
  }
}
