/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPrivacyPaymentAccount,
  IPrivacyPaymentAccountInterface,
} from "../../../contracts/AccountFactory.sol/IPrivacyPaymentAccount";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "privacyTree",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPrivacyPaymentAccount__factory {
  static readonly abi = _abi;
  static createInterface(): IPrivacyPaymentAccountInterface {
    return new Interface(_abi) as IPrivacyPaymentAccountInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPrivacyPaymentAccount {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPrivacyPaymentAccount;
  }
}
